function T = DH_link(alpha, a, theta, d)
T = T_rotate('x', alpha)*T_translate(a, 0, 0)*T_rotate('z', theta)*...
    T_translate(0, 0, d);

function T = T_rotate(axis, angle)
if axis == 'x'
    T = [1, 0, 0, 0;...
         0, cos(angle), -sin(angle), 0;...
         0, sin(angle), cos(angle), 0;...
         zeros(1, 3), 1];
elseif axis == 'y'
    T = [cos(angle), 0, sin(angle), 0;...
         0, 1, 0, 0;...
         -sin(angle), 0, cos(angle), 0;...
         zeros(1, 3), 1];
elseif axis == 'z'
    T = [cos(angle), -sin(angle), 0, 0;...
         sin(angle), cos(angle), 0, 0;...
         0, 0, 1, 0;...
         zeros(1, 3), 1];
else
    T = 0;
end

function T = T_translate(x, y, z)
T = [eye(3),[x; y; z];zeros(1,3),1];